version: '3.8'
services:
  mysqldb:
    image: mysql:8.0.29
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=facebook
      - PORT=3306
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network
  app:
    depends_on:
      - mysqldb
    build: ./server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 8080:8080
    environment:
      - HOST=mysqldb
      - USER=root
      - PASSWORD=root
      - DB=facebook
      - DB_PORT=3306
      - PORT=8080
    stdin_open: true
    tty: true
    networks:
      - app-network
  client:
    depends_on:
      - app
    build: ./client
    env_file: ./.env
    environment:
      - API_URL=http://app:8080
    restart: unless-stopped
    ports:
      - 3000:80
    networks:
      - app-network
volumes:
  db:
networks:
  app-network:
    driver: bridge
    
