const a = {
  status_code: 200,
  success: { message: 'image uploaded', code: 200 },
  image: {
    name: 'EWDv8sgU4AESJ1Z',
    extension: 'png',
    width: '1920',
    height: '1080',
    size: 1502299,
    time: '1656833674',
    expiration: '0',
    adult: '8',
    status: '0',
    cloud: '0',
    vision: '1',
    likes: '0',
    description: null,
    original_exifdata: null,
    original_filename: 'EWDv8sgU4AESJ1Z.png',
    views_html: '0',
    views_hotlink: '1',
    access_html: '0',
    access_hotlink: '1656833681',
    file: { resource: [Object] },
    is_animated: 0,
    nsfw: 0,
    id_encoded: 'juX3lI',
    ratio: 1.7777777777777777,
    size_formatted: '1.5 MB',
    filename: 'juX3lI.png',
    url: 'https://iili.io/juX3lI.png',
    url_short: 'https://freeimage.host/',
    url_seo: 'https://freeimage.host/i/ewdv8sgu4aesj1z.juX3lI',
    url_viewer: 'https://freeimage.host/i/juX3lI',
    url_viewer_preview: 'https://freeimage.host/i/juX3lI',
    url_viewer_thumb: 'https://freeimage.host/i/juX3lI',
    image: {
      filename: 'juX3lI.png',
      name: 'juX3lI',
      mime: 'image/png',
      extension: 'png',
      url: 'https://iili.io/juX3lI.png',
      size: 1502299
    },
    thumb: {
      filename: 'juX3lI.th.png',
      name: 'juX3lI.th',
      mime: 'image/png',
      extension: 'png',
      url: 'https://iili.io/juX3lI.th.png'
    },
    medium: {
      filename: 'juX3lI.md.png',
      name: 'juX3lI.md',
      mime: 'image/png',
      extension: 'png',
      url: 'https://iili.io/juX3lI.md.png'
    },
    display_url: 'https://iili.io/juX3lI.md.png',
    display_width: '1920',
    display_height: '1080',
    views_label: 'views',
    likes_label: 'likes',
    how_long_ago: '22 minutes ago',
    date_fixed_peer: '2022-07-03 07:34:34',
    title: 'EWDv8sgU4AESJ1Z',
    title_truncated: 'EWDv8sgU4AESJ1Z',
    title_truncated_html: 'EWDv8sgU4AESJ1Z',
    is_use_loader: false
  },
  request: {
    type: 'file',
    action: 'upload',
    timestamp: '1656833558090',
    auth_token: '7a85187d637bab53cd4d45169d9ce47ac233e2fe',
    nsfw: '0'
  },
  status_txt: 'OK'
}